<?php

namespace AppBundle\Repository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * Función que devuelve las actividades para una página con un número de elementos
     */
    public function paginaActividades($pagina = 1, $numActivities = 3, $destacado = false){
        settype($pagina, "integer");
        if ($pagina < 1){
            $pagina = 1;
        }
        /*var_dump($pagina, $numActivities);die();*/
        $query = $this->createQueryBuilder('a')
            ->where("a.destacado >= :condition1")
            ->setParameter('condition1', $destacado)
            ->setFirstResult($numActivities*($pagina - 1))
            ->setMaxResults($numActivities)
            ->orderBy('a.fechaFin', 'DESC')
            ->getQuery();
        return $query->getResult();
    }
}
