<?php

namespace AppBundle\Repository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * Función que devuelve las actividades para una página con un número de elementos
     */
    public function paginaActividades($pagina = 1, $numActivities = 3){
        /*var_dump($pagina, $numActivities);die();*/
        $query = $this->createQueryBuilder('a')
            ->where('a.destacado = 1')
            ->setFirstResult($numActivities*($pagina - 1))
            ->setMaxResults($numActivities)
            ->orderBy('a.fechaFin', 'DESC')
            ->getQuery();
        return $query->getResult();
    }
}
