<?php

namespace AppBundle\Repository;

/**
 * AgrupacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgrupacionRepository extends \Doctrine\ORM\EntityRepository
{
}
