<?php

namespace AppBundle\Repository;

/**
 * AsociacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsociacionRepository extends \Doctrine\ORM\EntityRepository
{
}
