<?php

namespace AppBundle\Repository;

/**
 * ColectivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColectivoRepository extends \Doctrine\ORM\EntityRepository
{
}
