<?php

namespace AppBundle\Repository;

/**
 * ProgramaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramaRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * Función que devuelve los programas para una página con un número de elementos
     */
    public function paginaProgramas($pagina = 1, $numProgramas = 3){
        settype($pagina, "integer");
        if ($pagina < 1){
            $pagina = 1;
        }
        /*var_dump($pagina, $numProgramas);die();*/
        $query = $this->createQueryBuilder('a')
            ->setFirstResult($numProgramas*($pagina - 1))
            ->setMaxResults($numProgramas)
            ->orderBy('a.fecha', 'DESC')
            ->getQuery();
        return $query->getResult();
    }
}
