app:
    resource: '@AppBundle/Controller/'
    type: annotation
salir:
    path: /salir

radio:
    path: /radio
    defaults:  { _controller: AppBundle:Default:programas, page: 1 }

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"