<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUrgauzx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUrgauzx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUrgauzx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUrgauzx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUrgauzx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Urgauzx',
    'container.build_id' => 'ab9c0e7f',
    'container.build_time' => 1556098881,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUrgauzx');
